# Generated by Django 5.0.4 on 2024-06-11 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_otp_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='otp_device',
        ),
    ]
