# Generated by Django 5.0.4 on 2024-06-03 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_team_teamcaption_team_teamplayers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='teamcaption',
            new_name='head_coach',
        ),
        migrations.RemoveField(
            model_name='team',
            name='teamplayers',
        ),
        migrations.RemoveField(
            model_name='team',
            name='teamvisecaption',
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_of', to='events.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='vice_captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_captain_of', to='events.player'),
        ),
    ]
