# Generated by Django 5.0.4 on 2024-06-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_teamcaption_team_head_coach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(default='Unassigned', max_length=100),
        ),
    ]
