# Generated by Django 5.0.4 on 2024-06-04 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_player_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='team1_logo',
        ),
        migrations.RemoveField(
            model_name='event',
            name='team2_logo',
        ),
    ]
