# Generated by Django 5.0.4 on 2024-06-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_bet_potential_payout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='payment_intent',
        ),
        migrations.AddField(
            model_name='bet',
            name='odds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost')], default='PENDING', max_length=10),
        ),
    ]
