# Generated by Django 5.0.4 on 2024-06-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_bet_payment_intent_bet_odds_bet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
