# Generated by Django 5.0.4 on 2024-06-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportsname', models.CharField(max_length=50)),
                ('teamA', models.CharField(max_length=50)),
                ('teamB', models.CharField(max_length=50)),
                ('eventdate', models.DateField()),
                ('eventtime', models.TimeField()),
                ('description', models.TextField()),
                ('betprice', models.IntegerField()),
            ],
        ),
    ]
